[phases.setup]
nixPkgs = ["python312", "poetry"]

[phases.install]
cmds = [
  "pip install poetry",
  "poetry config virtualenvs.create false",
  "poetry install --no-interaction --no-ansi --no-dev"
]

[start]
cmd = "poetry run uvicorn src.backend.main:app --host 0.0.0.0 --port $PORT"

